version: '3.9'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      # MAKE SURE THE VARIABLE NAME MATCHES YOUR CODE EXACTLY
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000